//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApiFinalExam
{
    using System;
    using System.Collections.Generic;
    
    public partial class Request
    {
        public int Id_Person { get; set; }
        public int Id_Book { get; set; }
        public int Quantity { get; set; }
        public int InCharge { get; set; }
        public Nullable<int> Id_Seller { get; set; }
    
        public virtual Book Book { get; set; }
        public virtual Person Person { get; set; }
        public virtual Person Person1 { get; set; }
    }
}
